### ISSUE TITLE
User-can-select-by-category

### ISSUE THREAD

**Issue by DavidKyong** [DavidKyong/Street-Moda#1]
## ⚙️ Feature

> ##### Users will be able to choose from shoes and apparels and depending on which one they choose it will take them to the listings of their choice. 

## 📐 Functionality

> ##### When the user clicks on the shoes button, it will take them to all the listings that people posted for shoes. When the user clicks on the apparels button, it will take them to all the listings that people posted for apparels.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

.
![Screenshot 2023-07-26 at 2 49 10 PM](https://github.com/DavidKyong/Street-Moda/assets/77517004/3c87dc3f-6a6c-4ca7-ae03-588b96a28244)
![Screenshot 2023-07-26 at 2 49 20 PM](https://github.com/DavidKyong/Street-Moda/assets/77517004/b07f3bd1-f112-4446-8fdb-ca3f556251e2)
![Screenshot 2023-07-26 at 2 49 30 PM](https://github.com/DavidKyong/Street-Moda/assets/77517004/195a7900-0a4e-4f1e-af59-20fe5c15f4a1)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to render the homepage, with a sell, login, and sign up button at the top in the navbar. Within the gif, add two more buttons for shoes and apparels.
- [x] Create a page that renders the shoes and apparel page. Using conditional statements, depending on what button the user clicks, it should only render that page.
   - [x] Add an onClick to the apparel and shoes button
   - [x] The heading should either be shoes or apparel and the listings should match the heading. If not listings there, it will read "Currently no listings".
- [x] Once the buttons renders the correct page, work on the css to match the Figma. (DON'T GET STUCK ON CSS!)

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
